import Head from 'next/head'
import styles from '../../styles/Home.module.css'
import Link from 'next/link'
import Header from '../../components/Header/Header'
import Footer from '../../components/Footer'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <main className={styles.main}>
        
        <h1 className={styles.title}>
          First Blog Page
        </h1>

        <p className={styles.description}>
          First page loaded on the server side
        </p>

        <div className={styles.grid}>

        <Link href="/">
          <h3><a className={styles.button}>Back to home</a></h3>
        </Link>
        </div>
      </main>

 <Footer/>
    </div>
  )
}
